#!/usr/bin/env sh
# One-time M4 Max local setup for BrightVision self-dev (Ollama + env file).
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "== BrightVision M4 dogfood setup =="

if ! command -v ollama >/dev/null 2>&1; then
  echo "Install Ollama first: https://ollama.com/" >&2
  exit 1
fi

FAST="${DOGFOOD_FAST_MODEL:-deepseek-coder:6.7b}"
HEAVY="${DOGFOOD_HEAVY_MODEL:-qwen3.6:27b-q4_K_M}"

if [ ! -f local-llm.env ]; then
  cat > local-llm.env <<EOF
# Generated by scripts/setup-m4-dogfood.sh
OLLAMA_HOST=http://127.0.0.1:11434
DATA_MODEL=${HEAVY}
MODEL_ROUTER=1
FAST_MODEL=${FAST}
HEAVY_MODEL=${HEAVY}
EOF
  echo "Wrote local-llm.env (DATA_MODEL=${HEAVY}, router on)"
else
  echo "local-llm.env already exists — edit manually or remove and re-run"
fi

echo "Pulling Ollama models (may take a while)…"
ollama pull "${HEAVY}"
ollama pull "${FAST}"

git submodule update --init --recursive cecli 2>/dev/null || true

if [ ! -x .venv/bin/python3 ]; then
  echo "Run: source activate.sh"
else
  echo "venv OK"
fi

echo ""
echo "Next:"
echo "  source activate.sh"
echo "  yarn dogfood:check"
echo "  yarn tauri dev"
echo "  Settings → Sync from env files → Terminal → Local LLM → Start → Terminal → Start"
